### ISSUE TITLE
Meaning of "Fallback"

### ISSUE THREAD

**Issue by aboba** [vasilvv/webtransport#14]
The term "fallback" is not well enough defined.  It might be helpful to define a list of requirements that "fallback" transport (and APIs) must satisfy. 

As an example, if QUIC is not available,  but HTTP/2 over TCP is, it may be possible to utilize RFC 8441 and/or potential extensions to provide for multiple streams over TCP.  This would support a portion of the WebTransport API (e.g. reliable streams), but now loss on one stream will block other streams and some protocol functionality (e.g. datagrams) may not be available.  Does that mean that some WebTransport methods operate differently or are not available?  In some cases, developers might prefer to "fallback" to the existing WebSockets API with its message-orientation.

**Comment by kixelated** [comment]
I don't know where "fallback" is currently being used, but I agree, it's not a good idea to silently downgrade functionality.

The idea is that WebTransports implement one or more interfaces (mixins) based on capability. The only way to fallback to another transport is if it 1) supports the same interfaces required by the developer and 2) a fallback server is advertised.

My question is, does there even need to be a fallback mechanism? Would a developer be able to implement the fallback themselves, perhaps with a simple timeout on connect?

**Comment by DavidSchinazi** [comment]
Closing this issue because the fallback transport draft has been removed from this repository.
