### ISSUE TITLE
QuicTransport: 0-RTT and Origin Indication

### ISSUE THREAD

**Issue by kixelated** [vasilvv/webtransport#16]
[QuicTransport optionally supports 0-RTT](https://vasilvv.github.io/webtransport/draft-vvv-webtransport-quic.html#rfc.section.3.3) if there's a corresponding API for early data.

The WICG draft does not define any way to enable early data, and it probably shouldn't anyway. Early data complicates the API and exposes the user to potential security vulnerabilities if they misunderstand the risks.

However, one thing worth clarifying in relation to 0-RTT is the origin indication message. It must be safe to send the origin indication in 0-RTT for any API to support early data. I don't fully understand if this is true but my impression is that it would be safe.

As for APIs that only send application data in 1-RTT space, sending the origin indication message in 0-RTT would be a slight improvement. The server must buffer all streams until the origin indication has been processed, so sending the origin indication early would reduce that initial head-of-line blocking.

Could we clarify that origin indication CAN or SHOULD be sent in 0-RTT?

**Comment by kixelated** [comment]
The word that I'm missing is idempotent. If we make the origin/path handshake idempotent, then QuicTransport can support 0-RTT.

**Comment by DavidSchinazi** [comment]
Closing this issue because the QuicTransport draft has been removed from this repository.
