### ISSUE TITLE
QuicTransport: origin indication via transport parameters

### ISSUE THREAD

**Issue by kixelated** [vasilvv/webtransport#17]
QuicTransport identifies itself using an ALPN and both peers agree to transfer additional configuration via a client-initiated stream (ID 2).

I think it would be an improvement if this origin indication was moved into the QUIC transport parameters and exchanged via the TLS ClientHello.

There would be a few benefits (in no particular order):
1. A server can terminate an invalid origin/path prior to performing the expensive TLS handshake.
2. A server does not need to buffer stream data (inbound and outbound) waiting until stream 2 has arrived.
3. A load balancer can route new connections to the correct server based on the path in the ClientHello. Currently, a load balancer must terminate TLS and buffer all streams until it can parse stream 2 prior to making a routing decision.
4. QUIC stream IDs could be exposed to the application without the asterisks that stream 2 has already been used. 
5. The first client packet (ClientHello) must already be padded to 1200 bytes. The origin and path parameters would replace some of that padding and overall reduce the bandwidth for a new connection.

There would be a few downsides:
1. Long paths and origins could cause fragment the ClientHello message into multiple packets.
2. Requires [registering](https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-22.2) `webtransport_path` and `webtransport_origin`.
3. QUIC libraries need to expose or support the new transport parameters.

**Comment by kixelated** [comment]
One more downside:
4. The path and origin won't be encrypted. This leaks more than SNI and would especially be a problem if ESNI is the future.

Yeah, unfortunately I think this alone is a reason to stick with the stream 2 approach. Thanks for letting me think out loud!

**Comment by vasilvv** [comment]
Yeah, that's pretty much the reason why stream 2 exists (we tried a few ways to limit ourselves to transport params, but those didn't work out).  It's possible that we could use [ALPS](https://tools.ietf.org/html/draft-vvv-tls-alps-00) for this, but ALPS is still in very early stage, so it's hard to tell if it will be useful.
