### ISSUE TITLE
QuicTransport: Rejecting a path

### ISSUE THREAD

**Issue by kixelated** [vasilvv/webtransport#19]
The spec defines a way to reject an unsupported origin with a CONNECTION_CLOSE (which has its own problems) but it does not define a way to reject an unsupported path. It's left up to the application, presumably to send a custom message or custom CONNECTION_CLOSE error code.

I think that origin and path rejection should use the same rejection mechanism. Consistency will be important as new fields are added, potentially including user-defined fields. There are a few options:

1. Path and origin rejection uses CONNECTION_CLOSE with reserved codes.
2. Path and origin rejection uses a custom message containing an error code/message, sending CONNECTION_CLOSE upon receipt.
3. Path and origin rejection is handled by the application. 
4. Path and origin rejection use RESET_STREAM, sending CONNECTION_CLOSE upon receipt.

I'm actually in favor of 3. 

The browser still needs to populate the origin for security reasons. However, the server can terminate the connection however it sees fit; the reason why does not need to be communicated to QuicTransport or the browser. It's much simpler than defining error codes and is the minimal work to allow QUIC in a web environment.

**Comment by LPardue** [comment]
As mentioned on the PR, I think RESET_STREAM could also be effective.

**Comment by kixelated** [comment]
Added option 4! I like it more than option 1 and 2.

**Comment by DavidSchinazi** [comment]
Closing this issue because the QuicTransport draft has been removed from this repository.
