### ISSUE TITLE
Reconsider the design around header block size limit

### ISSUE THREAD

**Issue by vasilvv** [vasilvv/webtransport#20]
Reviewing #18, @LPardue wrote:

> It seems unfortunate if a client can force a server to buffer up to 1,048,576 bytes. Yes the server can hangup, but it would have to wait until the application-imposed limit was reached. It might be healthier for the block to begin with a total length field. That allows a server to early abort.

I do agree that this is annoying, but at the same time adding a field that's redundant 90% of the time feels... weird?  We should think more seriously about how to make header size limits work at some point (maybe using ALPS or something like that).

**Comment by DavidSchinazi** [comment]
Closing this issue because the QuicTransport draft has been removed from this repository.
